[package]
name = "check"
description = "check!() macro inspired by Catch2"
version = "0.0.1"
license = "BSD-2-Clause"
authors = ["Maarten de Vries <maarten@de-vri.es>"]

edition = "2018"

[dependencies]
check-macros = { version = "0.0.1", path = "check-macros" }
yansi = "0.5.0"
